### ISSUE TITLE
Color version of white on black logo?

### ISSUE THREAD

**Issue by Matt-Osborn** [Zsh-art/logo#3]
First off: This is great, I love ZSH and it deserves a good logo. It's awesome that y'all made one.

I was just wondering if you had considered making a color version of the white text on black background version?

I'm happy to whip one up and do a PR, but I thought I would ask first in case you wanted to do it yourself, since it is your artistic work.

Regardless, cheers and thanks for the logo!

-Matt

**Comment by jdorfman** [comment]
@Matt-Osborn go for it. Please provide png and SVG like the others.
